kind: Deployment
apiVersion: apps/v1
metadata:
  name: airflow
  labels:
    app.kubernetes.io/part-of: airflow
    app.kubernetes.io/name: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
  template:
    metadata:
      labels:
        app: airflow
    spec:
      restartPolicy: Always
      initContainers:
        - name: wait-for-airflow-migrations
          image: quay.io/osclimate/airflow:2.7.3-omdingest-1.2.2
          args:
            - airflow
            - db
            - migrate
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: AIRFLOW__CORE__EXECUTOR
              value: LocalExecutor
            - name: AIRFLOW__CORE__LOAD_EXAMPLES
              value: 'False'
            - name: DB_HOST
              value: airflow-postgresql
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: airflow-postgresql
                  key: postgresql-database
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: airflow-postgresql
                  key: postgresql-user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: airflow-postgresql
                  key: postgresql-password
          envFrom:
            - configMapRef:
                name: sso-env-config
            # - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
            #   value: 'postgresql://$(DB_USER):$(DB_PASS)@$(DB_HOST):5432/$(DB_NAME)'
            # - name: AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION
            #   value: 'True'
            # - name: AIRFLOW__API__AUTH_BACKENDS
            #   value: >-
            #     airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session
            # - name: AIRFLOW__OPENMETADATA_AIRFLOW_APIS__DAG_GENERATED_CONFIGS
            #   value: /opt/airflow/dag_generated_configs
            # - name: AIRFLOW__LINEAGE__BACKEND
            #   value: >-
            #     airflow_provider_openmetadata.lineage.backend.OpenMetadataLineageBackend
            # - name: AIRFLOW__LINEAGE__AIRFLOW_SERVICE_NAME
            #   value: airflow
            # - name: AIRFLOW__LINEAGE__AUTH_PROVIDER_TYPE
            #   value: openmetadata
            # - name: AIRFLOW__LINEAGE__JWT_TOKEN
            #   value: >-
            #     eyJraWQiOiJHYjM4OWEtOWY3Ni1nZGpzLWE5MmotMDI0MmJrOTQzNTYiLCJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJvcGVuLW1ldGFkYXRhLm9yZ1wiIiwic3ViIjoiaW5nZXN0aW9uLWJvdCIsImVtYWlsIjoiaW5nZXN0aW9uLWJvdEBvcGVubWV0YWRhdGEub3JnIiwiaXNCb3QiOnRydWUsInRva2VuVHlwZSI6IkJPVCIsImlhdCI6MTcwNjkwNjAzMCwiZXhwIjpudWxsfQ.f9ob5Zzrv0IIerLwhk9cDZtU9ELAbBA94NJ-Zv0Sy84NuG8adlDyU92Q7UtWC2qyT86IclctGK5-pkI11_yhP47VAJJCMpvME1JZKNIGUrc1oJxURolFGxcF1hTFIBUx6mKOjAF66HS9NMEEZbHt8QOt3emJDTS3TMlFSGrIC2Qui9w8Bnio0LOswteBbMyitgRYZfQv1lKjfJyqOp34KgNoXkFuCD4XoX37mPW6e_SMzZOX9L3m5qaUM_dugkGQr2Dt8jAXaXR8kRDJ7BigD6hFp1Z2nB4r7KbuyJ-4fLHiR7rK_1zE90a1UYZtDZVOiYTKu201QrXq0H8ilczHfQ
            # - name: AIRFLOW__LINEAGE__OPENMETADATA_API_ENDPOINT
            #   value: 'http://openmetadata:8585/api'
            # - name: AIRFLOW_CONN_S3
            #   value: 'aws://minioAdmin:minio1234@/?endpoint_url=http:%2F%2Fminio:9000'
            # - name: AIRFLOW_CONN_TRINO_CONNECTION
            #   value: 'trino://admin:@trino:8080/'
            # - name: API_BASE_URL
            #   value: >-
            #     https://keycloak.apps.osc-cl4.apps.$(NAMESPACE).org/realms/KeycloakRealm
            # - name: OAUTH_TOKEN_URL
            #   value: >-
            #     https://keycloak.apps.osc-cl4.apps.$(NAMESPACE).org/realms/KeycloakRealm/protocol/openid-connect/token
            # - name: OAUTH_AUTHORIZE_URL
            #   value: >-
            #     https://keycloak.apps.osc-cl4.apps.$(NAMESPACE).org/realms/KeycloakRealm/protocol/openid-connect/auth
            # - name: OAUTH_USER_INFO
            #   value: >-
            #     https://keycloak.apps.osc-cl4.apps.$(NAMESPACE).org/realms/KeycloakRealm/protocol/openid-connect/userinfo
            # - name: OAUTH_LOGOUT_REDIRECT_URL
            #   value: >-
            #     https://keycloak.apps.osc-cl4.apps.$(NAMESPACE).org/realms/KeycloakRealm/protocol/openid-connect/logout
            # - name: OAUTH_JWKS_URI
            #   value: >-
            #     https://keycloak.apps.osc-cl4.apps.$(NAMESPACE).org/realms/KeycloakRealm/protocol/openid-connect/certs
            # - name: CLIENT_ID
            #   value: osclimate-airflow
            # - name: CLIENT_SECRET
            #   value: NTI1hTfr8o0SAcAesblaeWN2kqfUiSA4
            # - name: OIDC_ISSUER
            #   value: >-
            #     https://keycloak.apps.osc-cl4.apps.$(NAMESPACE).org/realms
            # - name: AIRFLOW__WEBSERVER__RBAC
            #   value: 'False'
            # - name: AIRFLOW__WEBSERVER__AUTHENTICATE
            #   value: 'False'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
        - name: deploydagsfroms3
          image: 'quay.io/osclimate/minioclient:1.9'
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: DEPLOYMENT_TYPE
              value: init
            # - name: S3_BUCKET_URL
            #   valueFrom:
            #     secretKeyRef:
            #       name: dag-deployment
            #       key: s3-bucketurl
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: dag-deployment
                  key: s3-accesskey
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: dag-deployment
                  key: s3-secret_key
            - name: S3_BUCKET_URL
              value: http://minio:9000
          resources: {}
          volumeMounts:
            - name: mcconfig
              mountPath: /.mc
            - name: dags-data
              mountPath: /opt/airflow/dags
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      securityContext: {}
      containers:
        - resources:
            limits:
              cpu: '2'
              memory: 4Gi
            requests:
              cpu: '2'
              memory: 4Gi
          terminationMessagePath: /dev/termination-log
          name: airflow-web
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: AIRFLOW__CORE__EXECUTOR
              value: LocalExecutor
            - name: AIRFLOW__LOGGING__LOGGING_LEVEL
              value: DEBUG
            - name: AIRFLOW__CORE__LOAD_EXAMPLES
              value: 'False'
            - name: CURL_CA_BUNDLE
            - name: DB_HOST
              value: airflow-postgresql
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: airflow-postgresql
                  key: postgresql-database
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: airflow-postgresql
                  key: postgresql-user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: airflow-postgresql
                  key: postgresql-password
          # envFrom:
          #   - configMapRef:
          #       name: sso-env-config

            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              value: 'postgresql://$(DB_USER):$(DB_PASS)@$(DB_HOST):5432/$(DB_NAME)'
            - name: AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION
              value: 'True'
            - name: AIRFLOW__API__AUTH_BACKENDS
              value: >-
                airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session
            - name: AIRFLOW__OPENMETADATA_AIRFLOW_APIS__DAG_GENERATED_CONFIGS
              value: /opt/airflow/dag_generated_configs
            - name: AIRFLOW__LINEAGE__BACKEND
              value: >-
                airflow_provider_openmetadata.lineage.backend.OpenMetadataLineageBackend
            - name: AIRFLOW__LINEAGE__AIRFLOW_SERVICE_NAME
              value: airflow
            - name: AIRFLOW__LINEAGE__AUTH_PROVIDER_TYPE
              value: openmetadata
            - name: AIRFLOW__LINEAGE__JWT_TOKEN
              value: >-
                eyJraWQiOiJHYjM4OWEtOWY3Ni1nZGpzLWE5MmotMDI0MmJrOTQzNTYiLCJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJvcGVuLW1ldGFkYXRhLm9yZ1wiIiwic3ViIjoiaW5nZXN0aW9uLWJvdCIsImVtYWlsIjoiaW5nZXN0aW9uLWJvdEBvcGVubWV0YWRhdGEub3JnIiwiaXNCb3QiOnRydWUsInRva2VuVHlwZSI6IkJPVCIsImlhdCI6MTcwNjkwNjAzMCwiZXhwIjpudWxsfQ.f9ob5Zzrv0IIerLwhk9cDZtU9ELAbBA94NJ-Zv0Sy84NuG8adlDyU92Q7UtWC2qyT86IclctGK5-pkI11_yhP47VAJJCMpvME1JZKNIGUrc1oJxURolFGxcF1hTFIBUx6mKOjAF66HS9NMEEZbHt8QOt3emJDTS3TMlFSGrIC2Qui9w8Bnio0LOswteBbMyitgRYZfQv1lKjfJyqOp34KgNoXkFuCD4XoX37mPW6e_SMzZOX9L3m5qaUM_dugkGQr2Dt8jAXaXR8kRDJ7BigD6hFp1Z2nB4r7KbuyJ-4fLHiR7rK_1zE90a1UYZtDZVOiYTKu201QrXq0H8ilczHfQ
            - name: AIRFLOW__LINEAGE__OPENMETADATA_API_ENDPOINT
              value: http://openmetadata.$(NAMESPACE).svc.cluster.local:8585/api
            - name: AIRFLOW_CONN_S3
              value: 'aws://minioAdmin:minio1234@/?endpoint_url=http:%2F%2Fminio.$(NAMESPACE).svc.cluster.local:9000'
            - name: AIRFLOW_CONN_TRINO_CONNECTION
              value: trino://admin:@trino.$(NAMESPACE).svc.cluster.local:8080/
            - name: API_BASE_URL
              value: >-
                https://keycloak-$(NAMESPACE).apps.osc-cl4.apps.os-climate.org/realms/KeycloakRealm
            - name: OAUTH_TOKEN_URL
              value: >-
                https://keycloak-$(NAMESPACE).apps.osc-cl4.apps.os-climate.org/realms/KeycloakRealm/protocol/openid-connect/token
            - name: OAUTH_AUTHORIZE_URL
              value: >-
                https://keycloak-$(NAMESPACE).apps.osc-cl4.apps.os-climate.org/realms/KeycloakRealm/protocol/openid-connect/auth
            - name: OAUTH_USER_INFO
              value: >-
                https://keycloak-$(NAMESPACE).apps.osc-cl4.apps.os-climate.org/realms/KeycloakRealm/protocol/openid-connect/userinfo
            - name: OAUTH_LOGOUT_REDIRECT_URL
              value: >-
                https://keycloak-$(NAMESPACE).apps.osc-cl4.apps.os-climate.org/realms/KeycloakRealm/protocol/openid-connect/logout
            - name: OAUTH_JWKS_URI
              value: >-
                https://keycloak-$(NAMESPACE).apps.osc-cl4.apps.os-climate.org/realms/KeycloakRealm/protocol/openid-connect/certs
            - name: CLIENT_ID
              value: airflow
            - name: CLIENT_SECRET
              value: QiEZ6U5enz4YGp9alJg6Cw7g87RIEk4z
            - name: OIDC_ISSUER
              value: >-
                https://keycloak-$(NAMESPACE).apps.osc-cl4.apps.os-climate.org/realms/KeycloakRealm
            - name: AIRFLOW__WEBSERVER__RBAC
              value: 'False'
            - name: AIRFLOW__WEBSERVER__AUTHENTICATE
              value: 'False'
            - name: AIRFLOW__WEBSERVER__WEB_SERVER_MASTER_TIMEOUT
              value: '300'
            - name: AIRFLOW__WEBSERVER__WORKER_REFRESH_BATCH_SIZE
              value: '0'
            - name: AIRFLOW__WEBSERVER__WORKER_REFRESH_INTERVAL
              value: '0'
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: dags-data
              mountPath: /opt/airflow/dags
            - name: dags-generated-data
              mountPath: /opt/airflow/dag_generated_configs
            - name: dags-log
              mountPath: /opt/airflow/logs
            - name: airflowweb-config
              mountPath: /opt/airflow/webserver_config.py
              subPath: webserver_config.py
          terminationMessagePolicy: File
          image: quay.io/osclimate/airflow:2.7.3-omdingest-1.2.2
          args:
            - bash
            - '-c'
            - exec airflow webserver
        - resources:
            limits:
              cpu: '2'
              memory: 4Gi
            requests:
              cpu: '1'
              memory: 2Gi
          terminationMessagePath: /dev/termination-log
          name: scheduler
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: 'metadata.namespace'
            - name: AIRFLOW__CORE__EXECUTOR
              value: LocalExecutor
            - name: AIRFLOW__CORE__LOAD_EXAMPLES
              value: 'False'
            - name: DB_HOST
              value: airflow-postgresql
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: airflow-postgresql
                  key: postgresql-database
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: airflow-postgresql
                  key: postgresql-user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: airflow-postgresql
                  key: postgresql-password
          # envFrom:
          #   - configMapRef:
          #       name: sso-env-config
          
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              value: 'postgresql://$(DB_USER):$(DB_PASS)@$(DB_HOST):5432/$(DB_NAME)'
            - name: AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION
              value: 'True'
            - name: AIRFLOW__API__AUTH_BACKENDS
              value: >-
                airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session
            - name: AIRFLOW__OPENMETADATA_AIRFLOW_APIS__DAG_GENERATED_CONFIGS
              value: /opt/airflow/dag_generated_configs
            - name: AIRFLOW__LINEAGE__BACKEND
              value: >-
                airflow_provider_openmetadata.lineage.backend.OpenMetadataLineageBackend
            - name: AIRFLOW__LINEAGE__AIRFLOW_SERVICE_NAME
              value: airflow
            - name: AIRFLOW__LINEAGE__AUTH_PROVIDER_TYPE
              value: openmetadata
            - name: AIRFLOW__LINEAGE__JWT_TOKEN
              value: >-
                eyJraWQiOiJHYjM4OWEtOWY3Ni1nZGpzLWE5MmotMDI0MmJrOTQzNTYiLCJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJvcGVuLW1ldGFkYXRhLm9yZ1wiIiwic3ViIjoiaW5nZXN0aW9uLWJvdCIsImVtYWlsIjoiaW5nZXN0aW9uLWJvdEBvcGVubWV0YWRhdGEub3JnIiwiaXNCb3QiOnRydWUsInRva2VuVHlwZSI6IkJPVCIsImlhdCI6MTcwNjkwNjAzMCwiZXhwIjpudWxsfQ.f9ob5Zzrv0IIerLwhk9cDZtU9ELAbBA94NJ-Zv0Sy84NuG8adlDyU92Q7UtWC2qyT86IclctGK5-pkI11_yhP47VAJJCMpvME1JZKNIGUrc1oJxURolFGxcF1hTFIBUx6mKOjAF66HS9NMEEZbHt8QOt3emJDTS3TMlFSGrIC2Qui9w8Bnio0LOswteBbMyitgRYZfQv1lKjfJyqOp34KgNoXkFuCD4XoX37mPW6e_SMzZOX9L3m5qaUM_dugkGQr2Dt8jAXaXR8kRDJ7BigD6hFp1Z2nB4r7KbuyJ-4fLHiR7rK_1zE90a1UYZtDZVOiYTKu201QrXq0H8ilczHfQ
            - name: AIRFLOW__LINEAGE__OPENMETADATA_API_ENDPOINT
              value: http://openmetadata.$(NAMESPACE).svc.cluster.local:8585/api
            - name: AIRFLOW_CONN_S3
              value: 'aws://minioAdmin:minio1234@/?endpoint_url=http:%2F%2Fminio.$(NAMESPACE).svc.cluster.local:9000'
            - name: AIRFLOW_CONN_TRINO_CONNECTION
              value: trino://admin:@trino.$(NAMESPACE).svc.cluster.local:8080/
            - name: API_BASE_URL
              value: >-
                https://keycloak-$(NAMESPACE).apps.osc-cl4.apps.os-climate.org/realms/KeycloakRealm
            - name: OAUTH_TOKEN_URL
              value: >-
                https://keycloak-$(NAMESPACE).apps.osc-cl4.apps.os-climate.org/realms/KeycloakRealm/protocol/openid-connect/token
            - name: OAUTH_AUTHORIZE_URL
              value: >-
                https://keycloak-$(NAMESPACE).apps.osc-cl4.apps.os-climate.org/realms/KeycloakRealm/protocol/openid-connect/auth
            - name: OAUTH_USER_INFO
              value: >-
                https://keycloak-$(NAMESPACE).apps.osc-cl4.apps.os-climate.org/realms/KeycloakRealm/protocol/openid-connect/userinfo
            - name: OAUTH_LOGOUT_REDIRECT_URL
              value: >-
                https://keycloak-$(NAMESPACE).apps.osc-cl4.apps.os-climate.org/realms/KeycloakRealm/protocol/openid-connect/logout
            - name: OAUTH_JWKS_URI
              value: >-
                https://keycloak-$(NAMESPACE).apps.osc-cl4.apps.os-climate.org/realms/KeycloakRealm/protocol/openid-connect/certs
            - name: CLIENT_ID
              value: airflow
            - name: CLIENT_SECRET
              value: QiEZ6U5enz4YGp9alJg6Cw7g87RIEk4z
            - name: OIDC_ISSUER
              value: >-
                https://keycloak-$(NAMESPACE).apps.osc-cl4.apps.os-climate.org/realms/KeycloakRealm
            - name: AIRFLOW__WEBSERVER__RBAC
              value: 'False'
            - name: AIRFLOW__WEBSERVER__AUTHENTICATE
              value: 'False'
            - name: AIRFLOW__WEBSERVER__WEB_SERVER_MASTER_TIMEOUT
              value: '300'
            - name: AIRFLOW__WEBSERVER__WORKER_REFRESH_BATCH_SIZE
              value: '0'
            - name: AIRFLOW__WEBSERVER__WORKER_REFRESH_INTERVAL
              value: '0'
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: dags-data
              mountPath: /opt/airflow/dags
            - name: dags-generated-data
              mountPath: /opt/airflow/dag_generated_configs
            - name: dags-log
              mountPath: /opt/airflow/logs
          terminationMessagePolicy: File
          image: quay.io/osclimate/airflow:2.7.3-omdingest-1.2.2
          args:
            - bash
            - '-c'
            - exec airflow scheduler
        - name: mc
          image: 'quay.io/osclimate/minioclient:1.9'
          env:
            - name: DEPLOYMENT_TYPE
              value: sidecar
            # - name: S3_BUCKET_URL
            #   valueFrom:
            #     secretKeyRef:
            #       name: dag-deployment
            #       key: s3-bucketurl
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: dag-deployment
                  key: s3-accesskey
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: dag-deployment
                  key: s3-secret_key
            - name: S3_BUCKET_URL
              value: http://minio:9000
          resources:
            limits:
              cpu: '2'
              memory: 4Gi
            requests:
              cpu: '1'
              memory: 2Gi
          volumeMounts:
            - name: mcconfig
              mountPath: /.mc
            - name: dags-data
              mountPath: /opt/airflow/dags
            - name: dags-log
              mountPath: /opt/airflow/logs
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      volumes:
        - name: dags-data
          emptyDir: {}
        - name: dags-generated-data
          emptyDir: {}
        - name: dags-log
          emptyDir: {}
        - name: config
          emptyDir: {}
        - name: mcconfig
          emptyDir: {}
        - name: airflowweb-config
          configMap:
            name: airflow-sso-config
            defaultMode: 420
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%